name: Advanced Security Settings
description: GHAS settings policy for Opendex

resource: repository
configuration:
    advancedSecurity:
        secretScanning: true
        secretScanningPushProtection: true
